image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: -Dmaven.repo.local=.m2
  CNR_MAVEN_VERSION: 3.4.0

stages:
  - build
  - test
  - nexus
  - release
  - container
  - deploy

build_dev:
  stage: build
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - dev
  script:
    - mvn compile -DskipTests -Pdev -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

test:
  stage: test
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  script:
    - mvn -q test -DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn


nexus_dev:
  stage: nexus
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - dev
  script: mvn -q install -DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn



