image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: -Dmaven.repo.local=.m2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  CNR_MAVEN_VERSION: 3.4.0

services:
  - docker:dind

cache:
  key: $CI_COMMIT_SHORT_SHA
  paths:
    - .m2/repository/
    - target/app.war

stages:
  - deploy_snapshot
  - build_test_container
  - deploy_test_container
  - release
  - build_prod_container
  - deploy_prod_container


deploy_nexus_snapshot:
  stage: deploy_snapshot
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - dev
  script:
    - mvn clean compile package deploy -DskipTests -Pdev
    - cp ./target/*.war ./target/app.war


# branch TEST & DEMO

buildtestcontainer:
  stage: build_test_container
  tags:
    - shared
  only:
    - test
    - demo
  script:
    - echo "Running build image and push image"
    - docker build --file src/main/docker/Dockerfile -t docker.si.cnr.it/sprint-flows-$CI_COMMIT_REF_NAME .
    - docker push docker.si.cnr.it/sprint-flows-$CI_COMMIT_REF_NAME


deploydockertest01:
  stage: deploy_test_container
  image: scolagreco/alpine-ssh:latest
  tags:
    - shared
  only:
    - test
  script:
    - echo "Deploy to dockertest01"
    - sed -i "s/DOCKER_IMAGE_SED/spring-flows-test/g" ./src/main/docker/app.yml
    - sed -i "s/SPRING_PROFILES_ACTIVE_SED/cnr,swagger,test/g" ./src/main/docker/app.yml
    - sed -i "s/PORT_SED/1480/g" ./src/main/docker/app.yml
    - sshremote $SSH_CONNECT_DOCKERTEST01 "if [ -f  ''/sites/sprint-flows-test/app.yml'' ]; then docker-compose -p sprint-flows-test -f /sites/sprint-flows-test/app.yml down; fi && rm -rf /sites/sprint-flows-test && mkdir -p /sites/sprint-flows-test"
    - scpremote ./src/main/docker/app.yml $SSH_CONNECT_DOCKERTEST01:/sites/sprint-flows-test/app.yml
    - sshremote $SSH_CONNECT_DOCKERTEST01 "cd /sites/sprint-flows-test && docker-compose -p sprint-flows-test -f app.yml pull && docker-compose -p sprint-flows-test -f app.yml up -d"
  environment:
    name: dockertest01
    url: http://dockerwebtest01.si.cnr.it:1480

deploydockertest02:
  stage: deploy_test_container
  image: scolagreco/alpine-ssh:latest
  tags:
    - shared
  only:
    - test
  script:
    - echo "Deploy to dockertest02"
    - sed -i "s/DOCKER_IMAGE_SED/spring-flows-test/g" ./src/main/docker/app.yml
    - sed -i "s/SPRING_PROFILES_ACTIVE_SED/cnr,swagger,test/g" ./src/main/docker/app.yml
    - sed -i "s/PORT_SED/1480/g" ./src/main/docker/app.yml
    - sshremote $SSH_CONNECT_DOCKERTEST02 "if [ -f  ''/sites/sprint-flows-test/app.yml'' ]; then docker-compose -p sprint-flows-test -f /sites/sprint-flows-test/app.yml down; fi && rm -rf /sites/sprint-flows-test && mkdir -p /sites/sprint-flows-test"
    - scpremote ./src/main/docker/app.yml $SSH_CONNECT_DOCKERTEST02:/sites/sprint-flows-test/app.yml
    - sshremote $SSH_CONNECT_DOCKERTEST02 "cd /sites/sprint-flows-test && docker-compose -p sprint-flows-test -f app.yml pull && docker-compose -p sprint-flows-test -f app.yml up -d"
  environment:
    name: dockertest02
    url: http://dockerwebtest02.si.cnr.it:1480

#release_war:
#  stage: release
#  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
#  script:
#    - mvn -Dresume=false release:prepare release:perform -Pprod -DskipTests -DpushChanges=false -DlocalCheckout=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Darguments="-Dmaven.javadoc.skip=true -DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

release_artifact:
  stage: release
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - master
  script:
    - git checkout -B "$CI_BUILD_REF_NAME"
    # mi metto in condizione del push per l'utente con la deploy key
    - git remote set-url --push origin git@git.si.cnr.it:$CI_PROJECT_PATH
    - mvn -Dresume=false release:prepare release:perform -Pprod -DpushChanges=false -DlocalCheckout=true
    - git push --tags
    - git commit --amend -m "[ci skip] prepare for next development iteration"
    - git push
  when: manual
  allow_failure: false


buildprodcontainer:
  stage: build_prod_container
  tags:
    - shared
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
  script:
    - echo "Running build image and push image for latest release"
    - docker build --file src/main/docker/Dockerfile -t docker.si.cnr.it/sprint-flows  .
    - docker push docker.si.cnr.it/sprint-flows
    - echo "Running build image and push image for release tag"
    - echo $CI_COMMIT_TAG
    - docker build --file src/main/docker/Dockerfile -t docker.si.cnr.it/sprint-flows:$CI_COMMIT_TAG .
    - docker push docker.si.cnr.it/sprint-flows:$CI_COMMIT_TAG


deploydockprod01:
  stage: deploy_prod_container
  image: scolagreco/alpine-ssh:latest
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
  tags:
    - shared
  when: manual
  script:
    - echo "Deploy sprint-flows to dockprod01"
    - echo "setting secrets"
    - sed -i "s/docker.si.cnr.it\/sprint-flows/docker.si.cnr.it\/sprint-flows:$CI_COMMIT_TAG/g" ./src/main/docker/app-prod.yml
    - sed -i "s/SPRING_DATASOURCE_PASSWORD_SED/$POSTGRESS_PASSWORD/g" ./src/main/docker/app-prod.yml
    - sed -i "s/SPRING_LDAP_MANAGERPASSWORD_SED/$LDAP_PASSWORD/g" ./src/main/docker/app-prod.yml
    - sed -i "s/ACE_PASSWORD_SED/$ACE_PASSWORD/g" ./src/main/docker/app-prod.yml
    - echo "stopping service"
    - sshremote $SSH_CONNECT_DOCPROD01 "if [ -f  ''/sites/docker-flows/app.yml'' ]; then docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml down; fi && rm -rf /sites/docker-flows/ && mkdir -p /sites/docker-flows/"
    - echo "copying docker-compose file"
    - scpremote ./src/main/docker/app-prod.yml $SSH_CONNECT_DOCPROD01:/sites/docker-flows/app.yml
    - echo "starting service"
    - sshremote $SSH_CONNECT_DOCPROD01 "docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml pull && docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml up -d"
  environment:
    name: dockprod01
    url: http://dockprod01.cedrc.cnr.it:1480

deploydockprod02:
  stage: deploy_prod_container
  image: scolagreco/alpine-ssh:latest
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
  when: manual
  script:
    - echo "Deploy sprint-flows to dockprod02"
    - echo "setting secrets"
    #    - sed -i "s/docker.si.cnr.it\/sprint-flows/docker.si.cnr.it\/sprint-flows:LATEST/g" ./src/main/docker/app-prod.yml
    - sed -i "s/SPRING_DATASOURCE_PASSWORD_SED/$POSTGRESS_PASSWORD/g" ./src/main/docker/app-prod.yml
    - sed -i "s/SPRING_LDAP_MANAGERPASSWORD_SED/$LDAP_PASSWORD/g" ./src/main/docker/app-prod.yml
    - sed -i "s/ACE_PASSWORD_SED/$ACE_PASSWORD/g" ./src/main/docker/app-prod.yml
    - echo "stopping service"
    - sshremote $SSH_CONNECT_DOCPROD02 "if [ -f  ''/sites/docker-flows/app.yml'' ]; then docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml down; fi && rm -rf /sites/docker-flows/ && mkdir -p /sites/docker-flows/"
    - echo "copying docker-compose file"
    - scpremote ./src/main/docker/app-prod.yml $SSH_CONNECT_DOCPROD02:/sites/docker-flows/app.yml
    - echo "starting services"
    - sshremote $SSH_CONNECT_DOCPROD02 "docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml pull && docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml up -d"
  environment:
    name: dockprod02
    url: http://dockprod02.cedrc.cnr.it:1480
