image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: -Dmaven.repo.local=.m2 -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  CNR_MAVEN_VERSION: 3.4.0

services:
  - docker:dind

cache:
  key: $CI_COMMIT_SHORT_SHA
  paths:
    - .m2/repository/
    - target/app.war

stages:
  - build
  - test
  - nexus
  - release
  - container
  - deploy


# all branches

test:
  stage: test
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  script:
    - mvn -q test -DskipTests


# branch DEV

build_dev:
  stage: build
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - dev
  script:
    - mvn clean compile package -DskipTests -Pdev
    - cp ./target/*.war ./target/app.war


# branch TEST & DEMO

build:
  stage: build
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - test
    - demo
  script:
    - mvn clean compile package -DskipTests -Pprod
    - cp ./target/*.war ./target/app.war

container:
  stage: container
  only:
    - test
    - demo
  script:
    - echo "Running build image and push image"
    - apt install libxml2-utils
    - POM_VERSION=`xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml`
    - docker build --file src/main/docker/demo-cnr/Dockerfile -t docker.si.cnr.it/sprint-flows-$CI_COMMIT_REF_NAME:$POM_VERSION .
    - docker push docker.si.cnr.it/sprint-flows-test

container_demo:
  stage: container
  tags:
    - shared
  only:
    - demo
  script:
    - echo "Running build image and push image"
    - docker build --file src/main/docker/demo-cnr/Dockerfile -t docker.si.cnr.it/sprint-flows-demo .
    - docker push docker.si.cnr.it/sprint-flows-demo

release_war:
  stage: release
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  script:
    - mvn -Dresume=false release:prepare release:perform -Pprod -DskipTests -DpushChanges=false -DlocalCheckout=true -Darguments="-Dmaven.javadoc.skip=true -DskipTests"


# branch MASTER

build_prod:
  stage: build
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - test
    - demo
  script:
    - mvn clean compile package -DskipTests -Pprod -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - cp ./target/*.war ./target/app.war
  artifacts:
    paths:
      - ./target/app.war
    expire_in: 1 day

deploydockprod:
  stage: deploy
  image: scolagreco/alpine-ssh:latest
  only:
    - master
  tags:
    - shared
  when: manual
  script:
    - echo "Deploy sprint-flows to dockprod01 & dockprod02"
    - echo "setting secrets"
    #    - sed -i "s/docker.si.cnr.it\/sprint-flows/docker.si.cnr.it\/sprint-flows:LATEST/g" ./src/main/docker/app-prod.yml
    - sed -i "s/SPRING_DATASOURCE_PASSWORD_SED/$POSTGRESS_PASSWORD/g" ./src/main/docker/app-prod.yml
    - sed -i "s/SPRING_LDAP_MANAGERPASSWORD_SED/$LDAP_PASSWORD/g" ./src/main/docker/app-prod.yml
    - sed -i "s/ACE_PASSWORD_SED/$ACE_PASSWORD/g" ./src/main/docker/app-prod.yml
    - echo "stopping services"
    - sshremote $SSH_CONNECT_DOCPROD01 "if [ -f  ''/sites/docker-flows/app.yml'' ]; then docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml down; fi && rm -rf /sites/docker-flows/ && mkdir -p /sites/docker-flows/"
    - sshremote $SSH_CONNECT_DOCPROD02 "if [ -f  ''/sites/docker-flows/app.yml'' ]; then docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml down; fi && rm -rf /sites/docker-flows/ && mkdir -p /sites/docker-flows/"
    - echo "copying docker-compose file"
    - scpremote ./src/main/docker/app-prod.yml $SSH_CONNECT_DOCPROD01:/sites/docker-flows/app.yml
    - scpremote ./src/main/docker/app-prod.yml $SSH_CONNECT_DOCPROD02:/sites/docker-flows/app.yml
    - echo "starting services"
    - sshremote $SSH_CONNECT_DOCPROD01 "docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml pull && docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml up -d"
    - sshremote $SSH_CONNECT_DOCPROD02 "docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml pull && docker-compose -p $CI_PROJECT_NAME -f /sites/docker-flows/app.yml up -d"
  environment:
    name: dockprod01
    url: http://dockprod01.cedrc.cnr.it:1480
