image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: -Dmaven.repo.local=.m2
  CNR_MAVEN_VERSION: 3.4.0

services:
  - docker:dind

cache:
  key: $CI_COMMIT_SHORT_SHA
  paths:
    - .m2/repository/
    - target/app.war

stages:
  - build
  - test
  - nexus
  - release
  - container
  - deploy

build_dev:
  stage: build
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - dev
  script:
    - mvn clean compile package -DskipTests -Pdev -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - cp ./target/*.war ./target/app.war
  artifacts:
    paths:
      - ./target/app.war
    expire_in: 1 day

build:
  stage: build
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  except:
    - dev
  script:
    - mvn compile -DskipTests -Pprod -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

test:
  stage: test
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  script:
    - mvn -q test -DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - cp ./target/app.war ./target/app2.war

nexus_test:
  stage: nexus
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - test
  script: mvn -q install -DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

container_test:
  stage: container
  only:
    - test
  script:
    - echo "Running build image and push image"
    - docker build --file src/main/docker/demo-cnr/Dockerfile -t docker.si.cnr.it/sprint-flows-test .
    - docker push docker.si.cnr.it/sprint-flows-test

container_demo:
  stage: container
  tags:
    - shared
  only:
    - demo
  script:
    - echo "Running build image and push image"
    - docker build --file src/main/docker/demo-cnr/Dockerfile -t docker.si.cnr.it/sprint-flows-demo .
    - docker push docker.si.cnr.it/sprint-flows-demo

