image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: -Dmaven.repo.local=./.m2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  CNR_MAVEN_VERSION: 3.4.0

services:
  - docker:dind

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - .m2/repository/
    - ~/.npm
    - node/
    - node/modules/
    - src/main/webapp/bower_components
    - target/app.war

stages:
  - execute_prod_cmd

exec:
  stage: execute_prod_cmd
  image: scolagreco/alpine-ssh:latest
  only: 
    - CI
  script:
    - sshremote $SSH_CONNECT_DOCPROD01 "docker ps -a"
    - sshremote $SSH_CONNECT_DOCPROD02 "docker ps -a"



