image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: -Dmaven.repo.local=.m2
  CNR_MAVEN_VERSION: 3.4.0

stages:
  - build
  - test
  - nexus
  - release
  - container
  - deploy

build_dev:
  stage: build
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - dev
  script:
    - apt install nodejs -y
    - mvn compile -DskipTests -Pdev

test:
  stage: test
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  script:
    - mvn test


nexus_dev:
  stage: nexus
  image: docker.si.cnr.it/cnr-maven:$CNR_MAVEN_VERSION
  only:
    - dev
  script: mvn install



