---
document:
  name: "Scrivania Digitale"
  description: "La Scrivania Digitale è un’applicazione web che permette la gestione dei flussi Documentali all’interno di un Ente, di un'azienda  o di una qualsiasi realtà strutturata di medie e grandi dimensioni."
  tags:
    - "documentazione"
