cache:
  hazelcast:
    mancenter:
    port: 1481
    outboundPort: 1482

# inizio credenziali Alfresco
user:
  admin:
    username: app.scrivaniadigitale
    password:
# fine credenziali Alfresco

repository:
  base:
    url: https://gestdoc.cnr.it/alfresco/

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # l'url del db viene modificata all'avvio dell'applicazione a seconda del profilo (cnr => flows-cnr,
    # oiv => flows-oiv) in modo che l'applicazione punti un db diverso a seconda del profilo
    url: jdbc:postgresql://fullhostdb.src.cnr.it:5432/flows
    username: flows-cnr
    password:
  jpa:
    database-platform: it.cnr.si.domain.util.FixedPostgreSQL82Dialect
    database: POSTGRESQL
    show-sql: false
  proxy:
    OIL:
      username: admin
      password: ubiquitous
      url: http://helpwildfly.si.cnr.it:8080/rest/
      newProblem: pest
      instance: /HDSiper
  ldap:
    url: ldap://as11.cedrc.cnr.it:389
    managerDn: cn=mastercnrapp8,ou=account,o=CNR,c=it
    managerPassword:
  mail:
    url: "https://nuovascrivaniadigitale.cnr.it"

ace:
  url: https://api.ace.cnr.it/api/
  username: app.scrivaniadigitale
  password:

cnr:
  abil:
    url: https://attivitainternazionali.cnr.it
