# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
  context-path: /management
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

server:
  port: 8080

spring:
  application:
    name: flows
  profiles:
    # The commented value for `active` can be replaced with valid spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: prod
  jackson:
    serialization.write_dates_as_timestamps: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: it.cnr.si.config.hazelcast.HazelcastCacheRegionFactory
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  messages:
    basename: i18n/messages
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: XHTML
    enabled: false
  http:
    multipart:
      # File upload limit
      maxFileSize: 50Mb
      maxRequestSize: 50Mb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
  ldap:
    userSearchBase: o=cnr, c=it
    userSearchFilter: uid={0}

security:
  basic:
    enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
    #allowed-origins: "*"
    #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    #allowed-headers: "*"
    #exposed-headers:
    #allow-credentials: true
    #max-age: 1800
  mail:
    from: no-reply@nuovascrivaniadigitale.cnr.it
  swagger:
    title: sprint API
    description: sprint API documentation
    version: 0.0.1
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
  ribbon:
    # comma seperated list of profiles to show a ribbon on the GUI
    displayOnActiveProfiles: dev,test

ajp:
  port: 8099
  timeout: 120000

cache.hazelcast.port: 5701
cache.hazelcast.packages: it.cnr.si

cnr:
  activiti:
    diagram-font: DejaVu Sans
  sigla:
    usr: app.scrivaniadigitale
    psw: bubbazza
  coolflows:
    username: utente1
    password: HggHjhUIuhedfwUI788yasdfiuh897
  firma:
    signcertid: AS0
    typeotpauth: firma
    url: http://arss.cedrc.cnr.it:8080/ArubaSignService/ArubaSignService?wsdl
    pdfprofile: PADESBES
  mail:
    mail.host: smtp.cnr.it
    mail.protocol: smtp
    mail.port: 25
    mail.send.error.to: marcinireneusz.trycz@cnr.it
    mail.from: no-reply@scrivaniadigitale
  siper:
    url: https://siper.cnr.it/
    username: app.scrivaniadigitale
    password: bubbazza
  abil:
    username: app.scrivaniadigitale
    password: portacigliarancini2019
    url: http://dockerwebtest01.si.cnr.it:8088
    loginPath: /api/authenticate
    domandePath: /api/cambioStatoDomanda

jasper-report:
  dir-oiv: /src/main/resources/print/oiv-print/
  dir-cnr: /src/main/resources/print/cnr-print/

repository:
  base:
    url: http://as1dock.si.cnr.it:8080/alfresco/
org:
  apache:
    chemistry:
      opencmis:
        session:
          repository:
            id: -default-
        binding:
          atompub:
            url: ${repository.base.url}api/-default-/public/cmis/versions/1.1/atom
          browser:
            url: ${repository.base.url}api/-default-/public/cmis/versions/1.1/browser
          spi:
            type: atompub
          connecttimeout: 50000
          readtimeout: 3000000
          httpinvoker:
            classname: org.apache.chemistry.opencmis.client.bindings.spi.http.DefaultHttpInvoker

user:
  admin:
    username: admin
    password: admin

# File upload limit
multipart:
  maxFileSize: 50Mb
  maxRequestSize: 50Mb
