# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
  context-path: /management
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

server:
  port: 8080

spring:
  application:
    name: flows
  profiles:
    # The commented value for `active` can be replaced with valid spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: prod
  jackson:
    serialization.write_dates_as_timestamps: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # l'url del db viene modificata all'avvio dell'applicazione a seconda del profilo (cnr => flows-cnr,
    # oiv => flows-oiv) in modo che l'applicazione punti un db diverso a seconda del profilo
    url: jdbc:h2:file:./DB-H2/flows;DB_CLOSE_DELAY=-1
    username: flows
    password:
  jpa:
    database-platform: it.cnr.si.domain.util.FixedH2Dialect
    database: H2
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: it.cnr.si.config.hazelcast.HazelcastCacheRegionFactory
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  messages:
    basename: i18n/messages
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: XHTML
    enabled: false
  http:
    multipart:
      # File upload limit
      maxFileSize: 50Mb
      maxRequestSize: 50Mb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
  ldap:
    userSearchBase: o=cnr, c=it
    userSearchFilter: uid={0}

security:
  basic:
    enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
    #allowed-origins: "*"
    #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    #allowed-headers: "*"
    #exposed-headers:
    #allow-credentials: true
    #max-age: 1800
  mail:
    from: no-reply@nuovascrivaniadigitale.cnr.it
  swagger:
    title: sprint API
    description: sprint API documentation
    version: 0.0.1
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
  ribbon:
    # comma seperated list of profiles to show a ribbon on the GUI
    displayOnActiveProfiles: dev,test

ajp:
  port: 8099
  timeout: 120000


cnr:
  cache:
    hazelcast:
      port: 5701
      packages: it.cnr.si
  activiti:
    diagram-font: DejaVu Sans

oiv:
  mail:
    mail.host: smtp.cnr.it
    mail.protocol: smtp
    mail.port: 25
    mail.send.error.to:
    mail.from: no-reply@scrivaniadigitale
  usr: oiv
  psw: oivpw

jasper-report:
  dir-oiv: /src/main/resources/print/oiv-print/
  dir-cnr: /src/main/resources/print/cnr-print/

user:
  admin:
    username: admin
    password: admin

# File upload limit
multipart:
  maxFileSize: 50Mb
  maxRequestSize: 50Mb

