version: '2'
services:
    sprint-flows-cnr:
        image: docker.si.cnr.it/sprint-flows
        environment:
            - SPRING_PROFILES_ACTIVE=prod,cnr,swagger
            - SPRING_DATASOURCE_PASSWORD=SPRING_DATASOURCE_PASSWORD_SED
            - SPRING_LDAP_MANAGERPASSWORD=SPRING_LDAP_MANAGERPASSWORD_SED
            - ACE_PASSWORD=ACE_PASSWORD_SED
            - USER_ADMIN_PASSWORD=CMIS_PASSWORD
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 1480:8080
