version: '2'
services:
    sprint-flows-cnr:
        image: docker.si.cnr.it/sprint-flows
        environment:
            - TZ=Europe/Rome
            - SPRING_PROFILES_ACTIVE=keycloak,prod,cnr,swagger
            - SPRING_DATASOURCE_PASSWORD=SPRING_DATASOURCE_PASSWORD_SED
            - SPRING_LDAP_MANAGERPASSWORD=SPRING_LDAP_MANAGERPASSWORD_SED
            - ACE_PASSWORD=ACE_PASSWORD_SED
            - USER_ADMIN_PASSWORD=CMIS_PASSWORD
            - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=http://git.si.cnr.it/devops/configuration-repo.git
            - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=flows
            - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=CONFIG_REPO_TOKEN
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - CACHE_HAZELCAST_PUBLICIP=CACHE_HAZELCAST_PUBLICIP_SED
            - CACHE_HAZELCAST_MEMBERS=150.146.7.79:1481,150.146.7.52:1481
        ports:
            - 1480:8080
            - 1481:1481
            - 1482:1482
        logging:
            driver: "gelf"
            options:
                gelf-address: "udp://log.cedrc.cnr.it:3514"
                tag: "sprint-flows"
                gelf-compression-type: "gzip"
                gelf-compression-level: "3"
