version: '2'
services:
    sprint-flows-cnr:
        image: docker.si.cnr.it/DOCKER_IMAGE_SED
        environment:
            - SPRING_PROFILES_ACTIVE=SPRING_PROFILES_ACTIVE_SED
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - PORT_SED:8080
