version: '2'
services:
    sprint-flows-test_cnr:
#        image: docker.si.cnr.it/sprint-flows-test
        #todo: imagine locale (puntare a docker.si.cnr.it, da pushare)
        image: sprint-flows-test_cnr
        links:
            - sprint-flows-test_cnr-pg:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=test,cnr
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/activiti
            - SPRING_DATASOURCE_USERNAME=activiti
            - SPRING_DATASOURCE_PASSWORD=activitipw
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        command: java -Djava.security.egd=file:/dev/./urandom -jar /app.war
        ports:
            - 9200:8080
    sprint-flows-test_cnr-pg:
        image: postgres:9.6.9-alpine
        environment:
            - POSTGRES_USER=activiti
            - POSTGRES_PASSWORD=activitipw
        volumes:
           - /var/lib/postgresql/data
        ports:
            - 8485:5432