version: '2'
services:
    sprint-flows-demo_cnr:
        image: docker.si.cnr.it/sprint-flows-demo
#        image: sprint-flows-demo_cnr
        links:
            - sprint-flows-demo_cnr-pg:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=demo,cnr
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/activiti
            - SPRING_DATASOURCE_USERNAME=activiti
            - SPRING_DATASOURCE_PASSWORD=activitipw
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9200:8080
    sprint-flows-demo_cnr-pg:
        image: postgres:9.6.9-alpine
        environment:
            - POSTGRES_USER=activiti
            - POSTGRES_PASSWORD=activitipw
        volumes:
           - spring-flows-demo-cnr-pg-data:/var/lib/postgresql/data
        ports:
            - 8485:5432

volumes:
    spring-flows-demo-cnr-pg-data: